version: 2.1
orbs:
  gradle: circleci/gradle@1.0.10
_defaults: &defaults
  working_directory: ~/code
  environment:
    JVM_OPTS: -Xmx3200m
_gradle_checksum: &gradle_checksum
  name: Generate Cache Checksum
  command: >-
    find . -name 'build.gradle' | sort | xargs cat | shasum | awk '{print
    $1}' > /tmp/gradle_cache_seed
jobs:
  build-linux:
    docker:
      - image: circleci/openjdk:8-jdk-browsers@sha256:65fc6dd997c64ee63b68b27f27cd67b6a70649c71a86ae7500947158c49ac67c
    <<: *defaults
    steps:
      - checkout
      # We can't use gradle/with_cache because it does not include the .konan dir where there kotlin native compiler lives
      - run:
          <<: *gradle_checksum
      - restore_cache:
          key: >-
            gradle-{{ checksum "/tmp/gradle_cache_seed" }}-{{ checksum
            ".circleci/config.yml" }}-linux
      # Work-around kotlin native using an old version of libtinfo https://github.com/circleci/circleci-images/issues/430
      - run:
          name: Install libtinfo5
          command: sudo apt update && sudo apt install -y libtinfo5
      - run:
          name: Run Tests
          command: ./gradlew check
      - gradle/collect_test_results:
          test_results_path: build/test-results
          reports_path: build/reports
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              echo "$MAVEN_CENTRAL_SEC_RING" | base64 -d > $HOME/secring.gpg
              gpg --import --batch $HOME/secring.gpg
              ./gradlew publish -Psonatype.username="$SONATYPE_USERNAME" -Psonatype.password="$SONATYPE_PASSWORD" -Psigning.keyId=0E7A8B89 -Psigning.password="$MAVEN_CENTRAL_KEY_PASSPHRASE" -Psigning.secretKeyRingFile=$HOME/secring.gpg -Porg.gradle.parallel=false
            fi
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
            - ~/.konan
          key: >-
            gradle-{{ checksum "/tmp/gradle_cache_seed" }}-{{ checksum
            ".circleci/config.yml" }}-linux
  build-macos:
    macos:
      xcode: "11.3.1"
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: homebrew-2
      - run:
          name: Download Gpg
          command: brew install gpg
      - save_cache:
          paths:
            - /usr/local/Homebrew
          key: homebrew-2
      # We can't use gradle/with_cache because it incorrectly uses the same cache key from build-linux
      - run:
          <<: *gradle_checksum
      - restore_cache:
          key: >-
            gradle-{{ checksum "/tmp/gradle_cache_seed" }}-{{ checksum
            ".circleci/config.yml" }}-macos
      - run:
          name: Set Gradle props
          command: |
            touch gradle.properties && echo "org.gradle.jvmargs=-Xmx2g" >> gradle.properties
      - run:
          name: Run Tests
          command: ./gradlew macosTest iosX64Test
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              echo "$MAVEN_CENTRAL_SEC_RING" | base64 -D -o $HOME/secring.gpg
              gpg --import --batch $HOME/secring.gpg
              ./gradlew publishIosArm64PublicationToMavenRepository publishIosX64PublicationToMavenRepository publishIosX64PublicationToMavenRepository publishMacosPublicationToMavenRepository -Psonatype.username="$SONATYPE_USERNAME" -Psonatype.password="$SONATYPE_PASSWORD" -Psigning.keyId=0E7A8B89 -Psigning.password="$MAVEN_CENTRAL_KEY_PASSPHRASE" -Psigning.secretKeyRingFile=$HOME/secring.gpg -Porg.gradle.parallel=false
            fi
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
            - ~/.konan
          key: >-
            gradle-{{ checksum "/tmp/gradle_cache_seed" }}-{{ checksum
            ".circleci/config.yml" }}-macos
workflows:
  version: 2
  build:
    jobs:
      - build-linux:
          context: opensource-maven
      - build-macos:
          context: opensource-maven
