version: 2.1
orbs:
  gradle: circleci/gradle@3.0.0
  win: circleci/windows@5.0
_defaults: &defaults
  working_directory: ~/code
  environment:
    JVM_OPTS: -Xmx3200m
_gradle_checksum: &gradle_checksum
  name: Generate Cache Checksum
  command: >-
    find . -name 'build.gradle' | sort | xargs cat | shasum | awk '{print
    $1}' > /tmp/gradle_cache_seed
_gradle_checksum_windows: &gradle_checksum_windows
  name: Generate Cache Checksum (Windows)
  command: >-
    Get-ChildItem -Filter *.gradle* -Recurse | Get-FileHash | Out-File -FilePath ".circleci/gradle_cache_seed"
jobs:
  build-linux:
    docker:
      - image: cimg/openjdk:17.0.9@sha256:a36da58bce6d1b6c43984970acec45546e746e628969b1261d6700367aa6e8dc
    resource_class: xlarge
    <<: *defaults
    steps:
      - checkout
      # We can't use gradle/with_cache because it does not include the .konan dir where there kotlin native compiler lives
      - run:
          <<: *gradle_checksum
      - restore_cache:
          key: >-
            gradle-{{ checksum "/tmp/gradle_cache_seed" }}-{{ checksum
            ".circleci/config.yml" }}-linux
      - run:
          name: Build
          command: ./gradlew build
      - gradle/collect_test_results:
          test_results_path: build/test-results
          reports_path: build/reports
      - run:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              echo "$MAVEN_CENTRAL_SEC_RING" | base64 -d > $HOME/secring.gpg
              gpg --import --batch $HOME/secring.gpg
              ./gradlew dokkaJavadocCommonJar
              ./gradlew publish -PsonatypeUsername="$SONATYPE_USERNAME" -PsonatypePassword="$SONATYPE_PASSWORD" -Psigning.keyId="$MAVEN_CENTRAL_KEY_ID" -Psigning.password="$MAVEN_CENTRAL_KEY_PASSPHRASE" -Psigning.secretKeyRingFile=$HOME/secring.gpg --no-parallel
            fi
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
            - ~/.konan
          key: >-
            gradle-{{ checksum "/tmp/gradle_cache_seed" }}-{{ checksum
            ".circleci/config.yml" }}-linux
  build-macos:
    macos:
      xcode: "14.1.0"
    resource_class: macos.x86.medium.gen2
    <<: *defaults
    steps:
      - checkout
      # We can't use gradle/with_cache because it incorrectly uses the same cache key from build-linux
      - run:
          <<: *gradle_checksum
      - restore_cache:
          key: >-
            gradle-{{ checksum "/tmp/gradle_cache_seed" }}-{{ checksum
            ".circleci/config.yml" }}-macos
      - run:
          name: Build Apple
          command: ./gradlew buildApple
      - run:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              echo "$MAVEN_CENTRAL_SEC_RING" | base64 -D -o $HOME/secring.gpg
              ./gradlew dokkaJavadocCommonJar
              ./gradlew publishApple -PsonatypeUsername="$SONATYPE_USERNAME" -PsonatypePassword="$SONATYPE_PASSWORD" -Psigning.keyId="$MAVEN_CENTRAL_KEY_ID" -Psigning.password="$MAVEN_CENTRAL_KEY_PASSPHRASE" -Psigning.secretKeyRingFile=$HOME/secring.gpg --no-parallel
            fi
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
            - ~/.konan
          key: >-
            gradle-{{ checksum "/tmp/gradle_cache_seed" }}-{{ checksum
            ".circleci/config.yml" }}-macos
  build-windows:
    executor:
        name: win/default
        size: large
    steps:
      - checkout
      - run:
          <<: *gradle_checksum_windows
      - restore_cache:
          key: >-
            gradle-{{ checksum ".circleci/gradle_cache_seed" }}-{{ checksum
            ".circleci/config.yml" }}-windows
      - run:
          command: ./gradlew --no-daemon build -x wasmJsNodeTest -x wasmWasiNodeTest
          shell: bash.exe
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
            - ~/.konan
          key: >-
            gradle-{{ checksum ".circleci/gradle_cache_seed" }}-{{ checksum
            ".circleci/config.yml" }}-windows
workflows:
  version: 2
  build:
    jobs:
      - build-linux:
          filters:
            branches:
              ignore: main
      - build-macos:
          filters:
            branches:
              ignore: main
      - build-windows:
          filters:
            branches:
              ignore: main
      - build-linux:
          context: opensource-maven
          filters:
            branches:
              only: main
      - build-macos:
          context: opensource-maven
          filters:
            branches:
              only: main
